require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

pre_install do |installer|
  $RNMapboxMaps.pre_install(installer)
end

target 'ProximityApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    $RNMapboxMaps.post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Force all pods to use iOS 15.1 minimum
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        
        # Disable warnings as errors (this suppresses deprecation warnings)
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        
        # Force Swift 5 for all pods (avoids Swift 6 warnings)
        config.build_settings['SWIFT_VERSION'] = '5.0'
        
        # Suppress Swift 6 concurrency warnings
        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= '$(inherited)'
        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] << ' DISABLE_SWIFT_6_CONCURRENCY_CHECKS'
      end
      
      # Specific fix for react-native-safe-area-context
      if target.name == "react-native-safe-area-context"
        target.build_configurations.each do |config|
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/Headers/Public"'
          config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/Headers/Private"'
        end
      end
    end
  end
end